import { ref } from "vue";
import { HomeIcon, ArchiveBoxIcon, MapIcon, UserGroupIcon, DocumentTextIcon,
    BellIcon, MapPinIcon, UserPlusIcon, CogIcon } from "@heroicons/vue/24/solid/index.js";


export const settings = ref([
    {
        id: 1,
        description: "account-settings.manage-storages",
        icon: "storage",
        type: "routerLink",
        route: "/storage",
        adminNeeded: false,
        superAdminNeeded: false,
    },
    {
        id: 2,
        description: "account-settings.manage-households",
        icon: "home",
        type: "routerLink",
        route: "/household",
        adminNeeded: false,
        superAdminNeeded: false,
    },
    {
        id: 3,
        description: "account-settings.find-assembling-areas",
        icon: "map",
        type: "routerLink",
        route: "/map",
        adminNeeded: true,
        superAdminNeeded: false,
    },
    {
        id: 4,
        description: "account-settings.manage-emergency-groups",
        icon: "group",
        type: "routerLink",
        route: "/emergency-groups",
        adminNeeded: false,
        superAdminNeeded: true,
    },
    {
        id: 5,
        description: "account-settings.experience-journal",
        icon: "journal",
        type: "routerLink",
        route: "/experience-journal",
        adminNeeded: false,
        superAdminNeeded: false,
    },
    {
        id: 6,
        description: "account-settings.enable-notifications",
        icon: "notification",
        type: "toggleButton",
        toggleState: false,
        adminNeeded: false,
        superAdminNeeded: false,
    },
    {
        id: 7,
        description: "account-settings.enable-position-sharing",
        icon: "location",
        type: "toggleButton",
        toggleState: false,
        adminNeeded: false,
        superAdminNeeded: false,
    },
    {
        id: 8,
        description: "account-settings.show-storage-on-frontpage",
        type: "toggleButton",
        toggleState: false,
        adminNeeded: false,
        superAdminNeeded: false,
    },
    {
        id: 9,
        description: "account-settings.show-household-on-frontpage",
        type: "toggleButton",
        toggleState: false,
        adminNeeded: false,
        superAdminNeeded: false,
    },
    {
        id: 10,
        description: "account-settings.admin-settings",
        icon: "settings",
        type: "routerLink",
        toggleState: false,
        adminNeeded: true,
        superAdminNeeded: false,
    },
    {
        id: 11,
        description: "account-settings.invite-admins",
        icon: "addUser",
        type: "routerLink",
        toggleState: false,
        adminNeeded: false,
        superAdminNeeded: true,
    }
]);


export const iconMap = {
    home: HomeIcon,
    storage: ArchiveBoxIcon,
    map: MapIcon,
    group: UserGroupIcon,
    journal: DocumentTextIcon,
    notification: BellIcon,
    location: MapPinIcon,
    settings: CogIcon,
    addUser: UserPlusIcon,
};