name: CI Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main, dev ]

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Save node_modules for later jobs
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

  build:
    name: Build project
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run Unit Tests
        run: npm run test:unit

  # e2e-test:
  #   name: E2E Tests
  #   runs-on: ubuntu-latest
  #   needs: install
  #   container:
  #     image: cypress/browsers:node18.12.0-chrome106-ff106
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Install Cypress
  #       run: npx cypress install

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Run E2E Tests
  #       run: npm run test:e2e

  #     - name: Upload Cypress Videos
  #       if: always()
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: cypress-videos
  #         path: cypress/videos/

  #     - name: Upload Cypress Screenshots
  #       if: always()
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: cypress-screenshots
  #         path: cypress/screenshots/

  #     - name: Cache Cypress
  #       uses: actions/cache@v4
  #       with:
  #         path: /root/.cache/Cypress
          # key: cypress-${{ hashFiles('package-lock.json') }}
